name = "JuMPConverter"
uuid = "8688f9d9-1483-4eb8-83e1-9bdd47b3f0f9"
authors = ["Beno√Æt Legat <benoit.legat@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
DataFrames = "1.7"
JuMP = "1.29.3"
MathOptInterface = "1.48.0"
OrderedCollections = "1.7"
julia = "1.10"
